# Generated by Django 4.2.7 on 2023-12-02 04:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_reference_numner', models.CharField(max_length=69)),
                ('timestamp', models.TimeField(auto_now_add=True)),
                ('jumlah', models.BigIntegerField()),
                ('image_link', models.CharField(validators=[django.core.validators.RegexValidator(message='image can only be from', regex='https:\\/\\/[a-zA-Z0-9.-]+\\.supabase\\.co\\/[^\\/]+\\/[^\\/]+\\.(png|jpeg|jpg)')])),
                ('bank', models.CharField(validators=[django.core.validators.RegexValidator(message='TipSen hanya menggunakan Bank BCA, Mandiri dan BNI', regex='BCA|Mandiri|BNI')])),
            ],
        ),
    ]
