# Generated by Django 4.2.7 on 2023-12-02 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='payment_reference_numner',
            new_name='payment_reference_number',
        ),
    ]
