# Generated by Django 4.2.7 on 2023-12-10 13:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_rename_payment_reference_numner_payment_payment_reference_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='bank',
            field=models.CharField(validators=[django.core.validators.RegexValidator(message='TipSen hanya menggunakan Bank BCA, Mandiri atau BNI', regex='BCA|Mandiri|BNI')]),
        ),
    ]
