# Generated by Django 4.2.7 on 2023-12-11 11:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_payment_bank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='bank',
            field=models.CharField(validators=[django.core.validators.RegexValidator(message='TipSen hanya menggunakan Bank BCA, Mandiri dan BNI', regex='BCA|Mandiri|BNI')]),
        ),
    ]
