# Generated by Django 4.2.7 on 2023-12-02 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageModel',
        ),
    ]
