# Generated by Django 4.2.7 on 2023-12-02 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.RenameField(
            model_name='order',
            old_name='is_special_order',
            new_name='is_special_request',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='buyer',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(max_length=50),
        ),
    ]
