# Generated by Django 4.2.7 on 2023-12-01 13:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('image_link', models.CharField(validators=[django.core.validators.RegexValidator(code='invalid_image_link', message='Image must be from http or https with jpg, jpeg or png extension', regex='^https?://.*\\.(jpeg|jpg|png)$')])),
            ],
        ),
    ]
